import React from 'react';
import NavBar from './NavBar';
import Footer from './Footer';
import styles from '../styles/PrologoImpecables.module.css';

function PrologoImpecables() {
  return (
    <>
        
        <NavBar />
        <div className={styles.content}>
            <div className={styles.prologo}>
                <div className={styles.titulo}>
                    <h2>LOS IMPECABLES</h2>
                    <p>Prólogo</p>
                </div>
                <div className={styles.texto}>
                    <h2>Los frutos de la obsesión</h2>
                    <p> La perfección, como la santidad, es un horizonte remoto que, no por utópico, es menos irrenunciable para quien cifra allí su meta. Puro deseo inalcanzable que en su continua procrastinación se transforma en sendero. Un camino tortuoso entre los barrancos del error, las amenazas nocturnas de la falta, los accidentes del defecto o el traspié del equívoco. De allí que para transitarlo sea menester, más que cualidades, virtudes o talentos excepcionales, una férrea voluntad y, sobre todo, disciplina. Lo que comúnmente se llama perseverancia, pero que en un grado superlativo de efectividad no es más que una simple y llana neurosis obsesiva. De este obsesivo camino a la perfección —puede que hasta de alguna perversa forma de santidad— trata, querido lector, el libro que tienes entre manos. Neuróticos son, en efecto, sus protagonistas. O quizá, ya de plano, psicóticos. Pero en todo caso ese diagnóstico correría por cuenta de un profesional en la materia. Manuel y Buzo, “los impecables” que refiere el título.</p>
                    <p> Todo un acierto, casi tan grande como la reunión en un solo volumen de dos obras de ficción de naturaleza muy diversa u opuesta, si se quiere. Al menos en lo que hace a su temática, planteo formal y desarrollo estilístico. Dos ficciones autónomas que a primera vista no parecen tener nada en común, y sin embargo lo tienen y mucho. Ball boy. Tragedia en polvo de ladrillo (2013) es un relato largo o nouvelle hiperrealista, de ritmo sincopado y etilo seco, que descarga una historia concentrada a la velocidad con la que viaja una pelota a un lado y otro de la pista de tenis. La historia de Manuel, una suerte de negativo fotográfico del Bartleby el escribiente de Melville, que refiere hacerlo mejor, siempre mejor, y por eso sustituye la competición deportiva por el tardío oficio de recogepelotas, porque ese humilde arte sí le permitiría acaso alcanzar la perfección. Una historia que, conviene decirlo, su autora, Tatiana Goransky, resuelve con la contundencia y la eficacia de un jugador de Grand Slam.</p>
                    <p> Por otro lado, Don del agua (2010) es una fluida novela breve con elementos del fantástico que entreteje con morosa sabiduría varios cauces argumentales y varios registros discursivos (desde la investigación periodística y el cuaderno de bitácora al estudio antropológico, la novela de enigma, el relato de viajes o las leyendas orales) para desgranar la historia en dos generaciones de una saga maldita. La de los Expósito: un Rabdomante albino en los lindes del enanismo que oficia de padre, como hijo mayor, el Capitán de un inhóspito barco abandonado a la intemperie de su quimérica persecución, bautizado paradójicamente Reparo Candoroso —que también recuerda a otro célebre personaje de Melville, pero mejor no seguir por ahí—, y sobre todo el segundo heredero, Abel Expósito, un tenaz Buzo empecinado en conquistar finalmente el estigma de su linaje. Poco importa, llegado a este punto, si en su caso el don del agua es el arte de la radiestesia, un imposible tesoro sumergido o la apnea definitiva de la respiración subacuática. Lo que cuenta es el estricto método para alcanzarlo. Su riguroso entrenamiento o intransigente camino hacia una suerte de líquida santidad. Otro mérito de Goransky es la elaborada estructura formal escogida para desembocar en un cauce único de flujo argumental: dada la naturaleza de las historias que componen Don del agua, el riesgo de que se escurrieran diluidas entre los dedos del lector era alto.</p>
                    <p> La presente edición en un solo volumen de estas dos obras de apariencia antitéticas originalmente publica das en Argentina en las fechas referidas) es un acierto, decíamos, porque juntas dialogan soterradamente, revelando su verdadera sustancia narrativa, idéntica en ambos casos más allá de sus evidentes diferencias formales. Así como “los impecables” que la protagonizan, Manuel y Buzo, quienes comparten algo más que un aire de familia. Del latín impeccabilis, el vocablo designa etimológicamente a la persona o cosa exenta de tacha, al incapaz de pecar, sin posibilidad de falta u error. Y eso son en esencia estos dos antihéroes inmaculados en su obsesiva carrera hacia la pureza de la perfección. Un premio imposible, siempre postergado, que ambos persiguen con el estricto cumplimiento de normas y reglas escritas.</p>
                    <p> Y esto no es azaroso. El “Código universal del buen Ball boy” en un caso y el “Manual de Buzo” en el otro. Al llegar aquí cabría preguntarse si esta neurótica obsesión tiene algún objeto en la vida real, más allá de la letra de molde. En la ficción está claro que es la condena de ambos personajes. O la particular variante de su propia autodestrucción. Y lo único impecable entre las solapas de este libro, en definitiva, es la prosa sin tacha de la autora.</p>
                    <p> Quizá sea arriesgado, tantos años después de que Roland Barthes planteara aquello de la muerte del autor, el sutil desplazamiento que supone interrogarse por el origen de esta curiosa obstinación que atraviesa a los protagonistas de ambas historias, pero igualmente es lícito hacerlo. Los mismos relatos dan una respuesta: proponen a su vez textos escritos, ya sean normativas, códigos o manuales, como la única actualización posible de esa irreprochable perfección ansiada. Cosa que desplaza a la inmaculada pureza de lo impecable hacia la escritura.</p>
                    <p> Sospecho que el mismo impulso estéril que empuja a ambos protagonistas a su perdición es el que gobierna la fértil escritura de Tatiana Goransky, como si de una suerte de maníaca discípula de Flaubert y su mot juste se tratara, en pleno siglo xxi. Apenas conocida en España por la publicación de ¿Quién mató a la cantante de jazz?, una breve y original novela negra construida sobre una doble matriz lúdico musical, Goransky también revelaba ahí una faceta íntima de su poliédrica y curiosa personalidad: la de intérprete vocal de dicho género.</p>
                    <p> Ahora la escritora argentina revela otra, a su pesar. O tal vez sean sus creaciones de papel quienes lo hacen por ella, a traición: el obsesivo afán de perfección con el que ataca el folio en blanco. Una neurosis que se hace evidente sobre la impecable superficie de su prosa.</p>
                    <p> Algo que dice mucho más de su talento que la apenas disimulada influencia de César Aira en su apego a las distancias cortas, en el libérrimo manejo de todos los recursos técnicos y en sus sorprendentes o hasta disparatados giros narrativos. Porque la neurosis no es necesariamente sinónimo de patología, y neuróticos lo somos todos. Incluso el citado escritor de culto. Y a fin de cuentas la obsesión, en ciertas manos privilegiadas, también produce belleza.</p>
                    <p> Diego Gándara<br /> Barcelona, mayo de 2016</p>
                </div>
            </div>
        </div>
        <Footer />
    </>
  )
}

export default PrologoImpecables;